### ISSUE TITLE
Bug：tbox认证失败 服务器响应not found 点击以重试

### ISSUE THREAD

**Issue by Sikongdddl** [1357310795/JboxTransfer#1]
# Bug
## Date: 2024/3/1
jboxTransfer登录时显示tbox认证失败 服务器响应not found 点击以重试

**Comment by 1357310795** [comment]
https://pan.sjtu.edu.cn 能登录进去吗？可能没权限

**Comment by Sikongdddl** [comment]
登陆显示未找到指定用户

----- 原始邮件 -----
发件人: "1357310795" ***@***.***>
收件人: "1357310795/JboxTransfer" ***@***.***>
抄送: "Sikongdddl" ***@***.***>, "State change" ***@***.***>
发送时间: 星期五, 2024年 3 月 01日 下午 4:28:41
主题: Re: [1357310795/JboxTransfer] Bug：tbox认证失败 服务器响应not found 点击以重试 (Issue #1)

https://pan.sjtu.edu.cn 能登录进去吗？可能没权限

**Comment by 1357310795** [comment]
那就是没权限用新云盘，也就用不了这个转移工具

**Comment by Sikongdddl** [comment]
哈哈哈 我是2020级的本科生 入学比较晚所以没有用过旧云盘（pan.sjtu） 一直在用jbox.sjtu 前段时间偶尔收到了旧云盘的共享文件 才发现这个问题 所以感觉还蛮奇怪的

----- 原始邮件 -----
发件人: "1357310795" ***@***.***>
收件人: "1357310795/JboxTransfer" ***@***.***>
抄送: "Sikongdddl" ***@***.***>, "State change" ***@***.***>
发送时间: 星期二, 2024年 3 月 05日 下午 2:39:12
主题: Re: [1357310795/JboxTransfer] Bug：tbox认证失败 服务器响应not found 点击以重试 (Issue #1)

那就是没权限用新云盘，也就用不了这个转移工具
